import { TOOTH_ORDER } from "./constants.js";

export const COMPONENT_TABS = [
  { id: "mesh", label: "MESH" },
  { id: "assembly", label: "ASSEMBLY" },
  { id: "rests", label: "RESTS" },
  { id: "clasps", label: "CLASPS" },
  { id: "bars", label: "BARS" },
  { id: "plate", label: "PLATE" },
  { id: "major", label: "MAJOR CONNECTOR" },
  { id: "case-note", label: "CASE NOTE", kind: "form" }
];

export const ACTION_UPON_FAILURE = {
  PREVENT_PLACEMENT: "PreventPlacement",
  REMOVE_THEN_PLACE: "RemoveThenPlace"
};

export const COMPONENT_CATALOG = [
  {
    id: "mesh-tori",
    label: "Mesh Tori",
    shortLabel: "MT",
    icon: "../../assets/menu-icon/mesh/Mesh_Tori.png",
    tab: "mesh",
    requiresPresence: false,
    requiresMissing: true,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.PREVENT_PLACEMENT,
  },
  {
    id: "mesh-stripe",
    label: "Mesh Stripe",
    shortLabel: "MS",
    icon: "../../assets/menu-icon/mesh/Mesh_Stripe.png",
    tab: "mesh",
    requiresPresence: false,
    requiresMissing: true,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.PREVENT_PLACEMENT,
  },
  {
    id: "mesh-hole",
    label: "Mesh Hole",
    shortLabel: "MH",
    icon: "../../assets/menu-icon/mesh/Mesh_Hole.png",
    tab: "mesh",
    requiresPresence: false,
    requiresMissing: true,
    conflictsWith: ["rest-seat"],
    actionUponFailure: ACTION_UPON_FAILURE.PREVENT_PLACEMENT,
  },
  {
    id: "mesh-flange",
    label: "Mesh Flange",
    shortLabel: "MF",
    icon: "../../assets/menu-icon/mesh/Mesh_Flange.png",
    tab: "mesh",
    requiresPresence: false,
    requiresMissing: true,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.PREVENT_PLACEMENT,
  },
  {
    id: "mesh-cross",
    label: "Mesh Cross",
    shortLabel: "MC",
    icon: "../../assets/menu-icon/mesh/Mesh_Cross.png",
    tab: "mesh",
    requiresPresence: false,
    requiresMissing: true,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.PREVENT_PLACEMENT,
  },
  {
    id: "assembly-tbar",
    label: "T-bar",
    shortLabel: "TBA",
    icon: "../../assets/menu-icon/Assembly/Bars/Assembly_Tbar.png",
    section: "bars",
    tab: "assembly",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  // {
  //   id: "assembly-tbar-mod",
  //   label: "Mod. T-bar",
  //   shortLabel: "TBM",
  //   icon: "../../assets/menu-icon/Assembly/Bars/Assembly_TbarMod.png",
  //   section: "bars",
  //   tab: "assembly",
  //   requiresPresence: true,
  //   requiresMissing: false,
  //   conflictsWith: [],
  //   actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  // },
  {
    id: "assembly-ibar",
    label: "I-bar",
    shortLabel: "IBA",
    icon: "../../assets/menu-icon/Assembly/Bars/Assembly_Ibar.png",
    section: "bars",
    tab: "assembly",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  // {
  //   id: "assembly-rpi",
  //   label: "RPI",
  //   shortLabel: "RPI",
  //   icon: "../../assets/menu-icon/Assembly/Bars/Assembly_RPI.png",
  //   section: "bars",
  //   tab: "assembly",
  //   requiresPresence: true,
  //   requiresMissing: false,
  //   conflictsWith: ["assembly-circ"],
  //   actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  // },
  {
    id: "assembly-circ",
    label: "Simple",
    shortLabel: "CIR",
    icon: "../../assets/menu-icon/Assembly/Circum/Assembly_SimpleCircum.png",
    section: "circum",
    tab: "assembly",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: ["assembly-rpi"],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "assembly-circ-reverse",
    label: "Reverse Circum Assembly",
    shortLabel: "REV",
    icon: "../../assets/menu-icon/Assembly/Circum/Assembly_Reverse.png",
    section: "circum",
    tab: "assembly",
    hidden: true,
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "assembly-circ-ring-support",
    label: "Ring Support",
    shortLabel: "RSP",
    icon: "../../assets/menu-icon/Assembly/Circum/Assembly_RingSupp.png",
    section: "circum",
    tab: "assembly",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "assembly-circ-embrasure",
    label: "EMB",
    shortLabel: "EMB",
    icon: "../../assets/menu-icon/Assembly/Circum/Assembly_embrasure.png",
    section: "circum",
    tab: "assembly",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "assembly-circ-half-n-half",
    label: "Half & Half",
    shortLabel: "HNH",
    icon: "../../assets/menu-icon/Assembly/Circum/Assembly_halfNhalf.png",
    section: "circum",
    tab: "assembly",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "assembly-circ-multi",
    label: "Multi",
    shortLabel: "MUL",
    icon: "../../assets/menu-icon/Assembly/Circum/Assembly_multiCircum.png",
    section: "circum",
    tab: "assembly",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "rest-seat",
    label: "Rest Seat",
    shortLabel: "RS",
    icon: "../../assets/menu-icon/rest/Rest.png",
    tab: "rests",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: ["mesh-hole"],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "rest-onlay",
    label: "Onlay Rest",
    shortLabel: "OR",
    icon: "../../assets/menu-icon/rest/Rest_Onlay.png",
    tab: "rests",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "retainer-clasp",
    label: "Retainer",
    shortLabel: "CC",
    icon: "../../assets/menu-icon/clasps/Retainer_Clasp.png",
    tab: "clasps",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "reciprocating-clasp",
    label: "Reciprocating",
    shortLabel: "BC",
    icon: "../../assets/menu-icon/clasps/Recip_Clasp.png",
    tab: "clasps",
    requiresPresence: true,
    requiresMissing: false,
    // A tooth's reciprocating element is a single slot (Reciprocating.Tooth Type):
    // a reciprocating clasp OR a proximal/mesh plate, never both. Mutually exclusive
    // with the plates so placing one removes the other (no overlapping clasp+plate).
    conflictsWith: ["plate-prox", "plate-crossmesh"],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "ring-clasp",
    label: "Ring",
    shortLabel: "RC",
    icon: "../../assets/menu-icon/clasps/Retainer_Ring.png",
    tab: "clasps",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "bar-i",
    label: "I Bar",
    shortLabel: "IB",
    icon: "../../assets/menu-icon/Bars/Retainer_I-Bar.png",
    tab: "bars",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.PREVENT_PLACEMENT,
  },
  {
    id: "bar-s",
    label: "S Bar",
    shortLabel: "SB",
    icon: "../../assets/menu-icon/Bars/Retainer_S-Bar.png",
    tab: "bars",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.PREVENT_PLACEMENT,
  },
  {
    id: "bar-u",
    label: "U Bar",
    shortLabel: "UB",
    icon: "../../assets/menu-icon/Bars/Retainer_U-Bar.png",
    tab: "bars",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.PREVENT_PLACEMENT,
  },
  {
    id: "bar-y",
    label: "Y Bar",
    shortLabel: "YB",
    icon: "../../assets/menu-icon/Bars/Retainer_Y-Bar.png",
    tab: "bars",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.PREVENT_PLACEMENT,
  },
  {
    id: "bar-t",
    label: "T Bar",
    shortLabel: "TB",
    icon: "../../assets/menu-icon/Bars/Retainer_T-Bar.png",
    tab: "bars",
    hidden: true,
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.PREVENT_PLACEMENT,
  },
  {
    id: "plate-prox",
    label: "Proximal Plate",
    shortLabel: "PP",
    icon: "../../assets/menu-icon/Plates/Recip_Plate.png",
    tab: "plate",
    requiresPresence: true,
    requiresMissing: false,
    // One reciprocating element per tooth: a plate excludes the other plate AND a
    // reciprocating clasp (see reciprocating-clasp).
    conflictsWith: ["plate-crossmesh", "reciprocating-clasp"],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "plate-crossmesh",
    label: "Mesh Plate",
    shortLabel: "MP",
    icon: "../../assets/menu-icon/Plates/Recip_Crossmesh.png",
    tab: "plate",
    requiresPresence: true,
    requiresMissing: false,
    // One reciprocating element per tooth: a plate excludes the other plate AND a
    // reciprocating clasp (see reciprocating-clasp).
    conflictsWith: ["plate-prox", "reciprocating-clasp"],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "major-upper-palatal-strap",
    label: "Palatal Strap",
    shortLabel: "PS",
    icon: "../../assets/menu-icon/Connectors/Upper/MC_Palatal_Strap.png",
    section: "upper",
    tab: "major",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "major-upper-palatal-plate",
    label: "Palatal Plate",
    shortLabel: "PP",
    icon: "../../assets/menu-icon/Connectors/Upper/MC_Palatal_Plate.png",
    section: "upper",
    tab: "major",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "major-upper-palatal-hole",
    label: "A-P Strap",
    shortLabel: "PH",
    icon: "../../assets/menu-icon/Connectors/Upper/MC_Palatal_Hole.png",
    section: "upper",
    tab: "major",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "major-upper-horseshoe",
    label: "Horse shoe",
    shortLabel: "HS",
    icon: "../../assets/menu-icon/Connectors/Upper/MC_Horseshoe.png",
    section: "upper",
    tab: "major",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "major-upper-palatal-bar",
    label: "Palatal Bar",
    shortLabel: "PB",
    icon: "../../assets/menu-icon/Connectors/Upper/MC_Palatal_Bar.png",
    section: "upper",
    tab: "major",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "major-lower-lingual-bar",
    label: "Lingual Bar",
    shortLabel: "LB",
    icon: "../../assets/menu-icon/Connectors/Lower/MC_lingual_Bar.png",
    section: "lower",
    tab: "major",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "major-lower-lingual-plate",
    label: "Lingual Plate",
    shortLabel: "LP",
    icon: "../../assets/menu-icon/Connectors/Lower/MC_lingual_plate.png",
    section: "lower",
    tab: "major",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  {
    id: "major-lower-lingual-kennedy",
    label: "Lingual Kennedy",
    shortLabel: "LK",
    icon: "../../assets/menu-icon/Connectors/Lower/MC_lingual_kennedy.png",
    section: "lower",
    tab: "major",
    requiresPresence: true,
    requiresMissing: false,
    conflictsWith: [],
    actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  },
  // {
  //   id: "major-lower-cingulum-bar",
  //   label: "Cingulum Bar",
  //   shortLabel: "CB",
  //   icon: "../../assets/menu-icon/Connectors/Lower/MC_cingulum_bar.png",
  //   section: "lower",
  //   tab: "major",
  //   requiresPresence: true,
  //   requiresMissing: false,
  //   conflictsWith: [],
  //   actionUponFailure: ACTION_UPON_FAILURE.REMOVE_THEN_PLACE,
  // },
];

export const COMPONENT_BY_ID = new Map(COMPONENT_CATALOG.map((entry) => [entry.id, entry]));

export {
  cancelMeshInteractionDefer,
  deferMeshInteraction,
  ensureMeshPlacementsOnMissingTeeth,
  getComponentAssetReference,
  getDefaultMeshIdForDesignMode,
  getMeshPlacementImageSize,
  getMeshPlacementOffset,
  getMeshPlacementRenderScale,
  handleMeshCatalogDoubleClickApplyAll,
  handleMeshToolDoubleClick,
  isMeshComponent,
  meshHoleUniformScaleToothId,
  meshSelectionContextFromState,
} from "./components.mesh.js";

export {
  getCingulumAcSuggestionPointsForTooth,
  getRestPlacementAssetReference,
  getRestPlacementImageSize,
  getRestPlacementOffset,
  getRestPlacementRenderScale,
  getRestSuggestionPointsForTooth,
  getRestSuggestionRadius,
  getRestSuggestionSurfaces,
  isRestComponent,
} from "./components.rest.js";

export {
  ensurePlatePlacementsOnPresentTeeth,
  ensurePlatePlacementsOnPresentTeethInJaws,
  getDefaultPlateIdForDesignMode,
  getPlatePlacementImageSize,
  getPlatePlacementOffset,
  getPlatePlacementRenderScale,
  isPlateComponentId,
  syncReciprocatingPlatesToMajorConnector,
} from "./components.plate.js";

export {
  getRetainerClaspAssetReference,
  getReciprocatingClaspAssetReference,
  getRingClaspAssetReference,
  getRingClaspPlacementImageSize,
  getRingClaspPlacementOffset,
  getRetainerClaspPlacementImageSize,
  getRetainerClaspPlacementOffset,
  getRetainerClaspPlacementRenderScale,
  getRetainerClaspSuggestionPointsForTooth,
  getRetainerClaspSuggestionRadius,
  isReciprocatingClaspComponent,
  isRingClaspComponent,
  isRetainerClaspComponent,
  isClaspComponent,
} from "./components.clasp.js";

export {
  BAR_PLACEMENT_ANCHOR_SURFACE,
  getBarPlacementAnchorPointForTooth,
  getBarPlacementAssetReference,
  getBarPlacementImageSize,
  getBarPlacementOffset,
  getBarPlacementRenderScale,
  getBarPlacementSurfaceForTooth,
  getBarSuggestibleToothIdSet,
  hasMissingTeethOnBothSidesForBar,
  getBarUserOffset,
  isBarComponent,
  isBarPlacementSurface,
  pruneInvalidBarPlacementsInJaw,
} from "./components.bar.js";

export {
  getMinorConnectorAssetReference,
  getMinorConnectorImageSize,
  getMinorConnectorMidOffset,
  getMinorConnectorOffset,
  getMinorConnectorRenderScale,
} from "./components.minor.js";

export {
  CONNECTOR_EXTRA_OFFSET_SEED_BY_TOOTH,
  CONNECTOR_PLACEMENT_IMAGE_SIZE_BY_TOOTH,
  CONNECTOR_RENDER_SCALE_BY_JAW,
  CONNECTOR_RENDER_SCALE_BY_TEMPLATE_TOOTH,
  CONNECTOR_POSITION_IGNORE_MESH_PLATE_ANCHOR,
  augmentTeethForPalatalBarConnectorNeighbors,
  ensureMajorConnectorPlacementsOnSupportedTeeth,
  ensureMajorConnectorPlacementsOnSupportedTeethInJaws,
  ensurePalatalBarPlacementsOnConnectorTeeth,
  pruneInvalidMajorConnectorPlacementsInJaw,
  removeMajorPlacementsFromPalatalBarExcludedUpperTeeth,
  replaceUpperPalatalBarPlacementsWithPalatalHole,
  getDefaultMajorConnectorIdForDesignMode,
  getMajorConnectorAssetReference,
  getMajorConnectorNeighborMajorFlags,
  getMajorConnectorNeighborMajorFlagsLower,
  getMajorConnectorPlacementImageSize,
  getMajorConnectorPlacementOffset,
  getMajorConnectorRenderScaleMultiplier,
  hasPalatalBarPlacementOnUpperArch,
  hasPalatalHolePlacementOnUpperArch,
  hasPalatalStrapPlacementOnUpperArch,
  computePalatalStrapPolygonPoints,
  isMajorConnectorComponent,
  isMajorConnectorToothExcluded,
  isMajorConnectorPlacementSeparated,
  isPalatalBarMajorComponent,
  isPalatalHoleMajorComponent,
  isPalatalStrapMajorComponent,
  PALATAL_BAR_ARCH_OVERLAY,
  PALATAL_BAR_CONNECTOR_TOOTH_IDS,
  PALATAL_BAR_MAJOR_COMPONENT_ID,
  PALATAL_PLATE_ARCH_OVERLAY,
  PALATAL_PLATE_ARCH_OVERLAY_BY_INDEX,
  PALATAL_PLATE_MAJOR_COMPONENT_ID,
  PALATAL_BAR_SUPPRESS_OTHER_MAJOR_TOOTH_IDS,
  PALATAL_HOLE_ARCH_OVERLAY_LAYERS,
  PALATAL_HOLE_MAJOR_COMPONENT_ID,
  PALATAL_STRAP_ARCH_POLYGON,
  PALATAL_STRAP_MAJOR_COMPONENT_ID,
  getPalatalPlateArchOverlayFrame,
  getPalatalPlateOverlayIndexFromUpperPlacements,
  shouldMajorConnectorIgnoreMeshPlateAnchor,
  hasPalatalPlatePlacementOnUpperArch,
  isPalatalPlateMajorComponent,
  shouldUseMajorConnectorEndAsset,
  shouldUsePalatalBarSecondMolarDistalTemplate,
  toothHasMajorConnectorPlacement,
} from "./components.major.js";
